/**
 * Centralized teacher data module
 * Single source of truth for all mock data used across teacher dashboard pages.
 * Replace with API calls in production.
 */

// ─── Teacher Profile ────────────────────────────────────────────────
export const teacherProfile = {
    id: "TCH-2024-001",
    firstName: "Dr. Kebede",
    lastName: "Kassaye",
    email: "k.kassaye@smarttutorET.edu",
    avatar: null,
    initials: "KK",
    title: "Senior Mathematics Tutor",
    department: "Mathematics & Sciences",
    school: "Addis International School",
    bio: "Ph.D. in Applied Mathematics from Addis Ababa University. 12+ years teaching experience.",
    location: "Addis Ababa, Ethiopia",
    joinDate: "September 2018",
    totalStudents: 124,
    totalCourses: 5,
    rating: 4.9,
}

// ─── Managed Courses ────────────────────────────────────────────────
export const teacherCourses = [
    {
        id: 1,
        name: "Mathematics — Calculus",
        code: "MATH-401",
        grade: "Grade 12",
        studentsEnrolled: 32,
        capacity: 40,
        progress: 65,
        status: "active" as const,
        schedule: "Mon, Wed, Fri — 9:00 AM",
        image: "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=800&q=80",
        category: "Mathematics",
        color: "sky",
        avgGrade: 88,
        completionRate: 72,
        nextClass: "Monday, 9:00 AM",
        materials: 14,
    },
    {
        id: 2,
        name: "Mathematics — Algebra",
        code: "MATH-301",
        grade: "Grade 11",
        studentsEnrolled: 28,
        capacity: 35,
        progress: 80,
        status: "active" as const,
        schedule: "Tue, Thu — 10:30 AM",
        image: "https://images.unsplash.com/photo-1509228627152-72ae9ae6848d?w=800&q=80",
        category: "Mathematics",
        color: "indigo",
        avgGrade: 84,
        completionRate: 85,
        nextClass: "Tuesday, 10:30 AM",
        materials: 18,
    },
    {
        id: 3,
        name: "Statistics & Probability",
        code: "STAT-201",
        grade: "Grade 10",
        studentsEnrolled: 22,
        capacity: 30,
        progress: 45,
        status: "active" as const,
        schedule: "Mon, Wed — 2:00 PM",
        image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&q=80",
        category: "Mathematics",
        color: "emerald",
        avgGrade: 79,
        completionRate: 50,
        nextClass: "Wednesday, 2:00 PM",
        materials: 9,
    },
    {
        id: 4,
        name: "National Exam Prep — Maths",
        code: "MATH-EXAM",
        grade: "Grade 12",
        studentsEnrolled: 42,
        capacity: 50,
        progress: 30,
        status: "active" as const,
        schedule: "Sat — 8:00 AM",
        image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=800&q=80",
        category: "Exam Prep",
        color: "amber",
        avgGrade: 75,
        completionRate: 32,
        nextClass: "Saturday, 8:00 AM",
        materials: 7,
    },
    {
        id: 5,
        name: "Mathematics — Geometry",
        code: "MATH-201",
        grade: "Grade 9",
        studentsEnrolled: 30,
        capacity: 35,
        progress: 90,
        status: "completed" as const,
        schedule: "Tue, Thu — 8:00 AM",
        image: "https://images.unsplash.com/photo-1509228468518-180dd4864904?w=800&q=80",
        category: "Mathematics",
        color: "violet",
        avgGrade: 91,
        completionRate: 95,
        nextClass: "Completed",
        materials: 22,
    },
]

// ─── Assignments ────────────────────────────────────────────────────
export const teacherAssignments = [
    {
        id: 1,
        title: "Calculus Homework #4 — Integration",
        courseId: 1,
        courseName: "Mathematics — Calculus",
        courseCode: "MATH-401",
        dueDate: "2026-03-14",
        dueLabel: "Tomorrow",
        totalStudents: 32,
        submitted: 18,
        graded: 12,
        pending: 14,
        status: "active" as const,
        maxScore: 100,
        avgScore: 82,
        description: "Solve problems 1-15 from Chapter 8: Integration techniques by parts, substitution, and partial fractions.",
        attachments: ["homework_4.pdf"],
    },
    {
        id: 2,
        title: "Algebra Mid-term Quiz",
        courseId: 2,
        courseName: "Mathematics — Algebra",
        courseCode: "MATH-301",
        dueDate: "2026-03-18",
        dueLabel: "In 5 days",
        totalStudents: 28,
        submitted: 0,
        graded: 0,
        pending: 28,
        status: "active" as const,
        maxScore: 50,
        avgScore: 0,
        description: "Online quiz covering linear equations, inequalities, and functions (Chapters 3-5).",
        attachments: [],
    },
    {
        id: 3,
        title: "Statistics Project — Data Analysis",
        courseId: 3,
        courseName: "Statistics & Probability",
        courseCode: "STAT-201",
        dueDate: "2026-03-22",
        dueLabel: "In 9 days",
        totalStudents: 22,
        submitted: 4,
        graded: 0,
        pending: 18,
        status: "active" as const,
        maxScore: 100,
        avgScore: 0,
        description: "Collect a real-world dataset and perform descriptive statistics including mean, median, mode, and standard deviation. Present findings using charts.",
        attachments: ["project_guidelines.pdf", "data_template.xlsx"],
    },
    {
        id: 4,
        title: "Calculus Homework #3 — Derivatives",
        courseId: 1,
        courseName: "Mathematics — Calculus",
        courseCode: "MATH-401",
        dueDate: "2026-03-07",
        dueLabel: "Closed",
        totalStudents: 32,
        submitted: 30,
        graded: 30,
        pending: 2,
        status: "closed" as const,
        maxScore: 100,
        avgScore: 86,
        description: "Problems on chain rule, product rule, quotient rule, and implicit differentiation.",
        attachments: ["homework_3.pdf"],
    },
    {
        id: 5,
        title: "Geometry End-of-Term Exam",
        courseId: 5,
        courseName: "Mathematics — Geometry",
        courseCode: "MATH-201",
        dueDate: "2026-03-01",
        dueLabel: "Closed",
        totalStudents: 30,
        submitted: 30,
        graded: 30,
        pending: 0,
        status: "closed" as const,
        maxScore: 100,
        avgScore: 91,
        description: "Comprehensive exam covering all geometry topics for the semester.",
        attachments: [],
    },
]

// ─── Student Submissions ─────────────────────────────────────────────
export const submissions = [
    // Assignment 1 submissions
    { id: 1, assignmentId: 1, studentName: "Abebe Tadesse", studentId: "STU-001", submittedAt: "2026-03-13T08:32:00", status: "submitted" as const, score: null, feedback: null, files: ["abebe_hw4.pdf"] },
    { id: 2, assignmentId: 1, studentName: "Marta Bekele", studentId: "STU-002", submittedAt: "2026-03-12T22:10:00", status: "graded" as const, score: 92, feedback: "Excellent work! Clear method and good use of integration by parts.", files: ["marta_hw4.pdf"] },
    { id: 3, assignmentId: 1, studentName: "Yohannes Kemal", studentId: "STU-003", submittedAt: "2026-03-12T19:45:00", status: "graded" as const, score: 78, feedback: "Good attempt. Partial fractions section needs review.", files: ["yohannes_hw4.pdf"] },
    { id: 4, assignmentId: 1, studentName: "Hirut Dessie", studentId: "STU-004", submittedAt: "2026-03-13T10:05:00", status: "submitted" as const, score: null, feedback: null, files: ["hirut_hw4.pdf"] },
    { id: 5, assignmentId: 1, studentName: "Dawit Haile", studentId: "STU-005", submittedAt: "2026-03-11T14:20:00", status: "graded" as const, score: 88, feedback: "Good work overall. Minor algebraic error in problem 9.", files: ["dawit_hw4.pdf"] },
    { id: 6, assignmentId: 1, studentName: "Selamawit Girma", studentId: "STU-006", submittedAt: "2026-03-12T11:00:00", status: "graded" as const, score: 95, feedback: "Outstanding! Perfect solutions for all problems.", files: ["selamawit_hw4.pdf"] },
    { id: 7, assignmentId: 1, studentName: "Berhane Teklu", studentId: "STU-007", submittedAt: "2026-03-13T07:15:00", status: "submitted" as const, score: null, feedback: null, files: ["berhane_hw4.pdf"] },
    // Assignment 3 early submissions
    { id: 8, assignmentId: 3, studentName: "Liya Mengesha", studentId: "STU-101", submittedAt: "2026-03-13T09:00:00", status: "submitted" as const, score: null, feedback: null, files: ["liya_project.pdf", "liya_data.xlsx"] },
    { id: 9, assignmentId: 3, studentName: "Tigist Alemu", studentId: "STU-102", submittedAt: "2026-03-12T18:30:00", status: "submitted" as const, score: null, feedback: null, files: ["tigist_project.pdf"] },
]

// ─── Messages ───────────────────────────────────────────────────────
export const teacherMessages = [
    {
        id: 1,
        studentName: "Abebe Tadesse",
        studentId: "STU-001",
        course: "Mathematics — Calculus",
        lastMessage: "Can you explain the integration by parts formula again? I'm stuck on problem 12.",
        time: "10 min ago",
        unread: 2,
        avatar: null,
        initials: "AT",
        messages: [
            { id: 1, from: "student", text: "Hello Dr. Kassaye, I have a question about homework 4.", time: "9:15 AM" },
            { id: 2, from: "teacher", text: "Of course Abebe! Which problem are you stuck on?", time: "9:20 AM" },
            { id: 3, from: "student", text: "Problem 12 — I think I need to use integration by parts but I'm not sure how to split u and dv.", time: "9:22 AM" },
            { id: 4, from: "student", text: "Can you explain the integration by parts formula again? I'm stuck on problem 12.", time: "9:22 AM" },
        ],
    },
    {
        id: 2,
        studentName: "Selamawit Girma",
        studentId: "STU-006",
        course: "Mathematics — Calculus",
        lastMessage: "Thank you for the detailed feedback on my assignment!",
        time: "1h ago",
        unread: 0,
        avatar: null,
        initials: "SG",
        messages: [
            { id: 1, from: "student", text: "Thank you for the detailed feedback on my assignment!", time: "8:45 AM" },
            { id: 2, from: "teacher", text: "You're welcome! Keep up the excellent work.", time: "8:50 AM" },
        ],
    },
    {
        id: 3,
        studentName: "Yohannes Kemal",
        studentId: "STU-003",
        course: "Mathematics — Calculus",
        lastMessage: "Will there be a make-up class this Saturday?",
        time: "3h ago",
        unread: 1,
        avatar: null,
        initials: "YK",
        messages: [
            { id: 1, from: "student", text: "Good afternoon Dr. Kassaye.", time: "7:00 AM" },
            { id: 2, from: "student", text: "Will there be a make-up class this Saturday?", time: "7:01 AM" },
        ],
    },
    {
        id: 4,
        studentName: "Marta Bekele",
        studentId: "STU-002",
        course: "Mathematics — Calculus",
        lastMessage: "I submitted my project early. Can you take a look?",
        time: "Yesterday",
        unread: 0,
        avatar: null,
        initials: "MB",
        messages: [
            { id: 1, from: "student", text: "Hi Dr. Kassaye, I submitted my project early. Can you take a look?", time: "Yesterday 4:00 PM" },
            { id: 2, from: "teacher", text: "Great initiative Marta! I'll review it soon.", time: "Yesterday 5:30 PM" },
        ],
    },
]

// ─── Sent Announcements ──────────────────────────────────────────────
export const teacherAnnouncements = [
    {
        id: 1,
        title: "Upcoming Mock Exam Schedule — Calculus",
        body: "The mid-term mathematics mock exam is scheduled for next Tuesday, March 15. Please review calculus modules 1-8 and bring scientific calculators. The exam will be held in Hall A from 9:00 AM to 12:00 PM.",
        audience: "MATH-401",
        audienceLabel: "Mathematics — Calculus",
        sentAt: "2026-03-09",
        pinned: true,
        category: "academic" as const,
        readCount: 28,
        totalCount: 32,
    },
    {
        id: 2,
        title: "Homework #4 Submission Reminder",
        body: "Just a reminder that Homework #4 on Integration is due tomorrow (March 14) at 11:59 PM. Please submit via the student portal. Late submissions will incur a 10% penalty.",
        audience: "MATH-401",
        audienceLabel: "Mathematics — Calculus",
        sentAt: "2026-03-13",
        pinned: false,
        category: "academic" as const,
        readCount: 20,
        totalCount: 32,
    },
    {
        id: 3,
        title: "Additional Study Resources Posted",
        body: "I've uploaded additional practice problems and video solutions for Chapters 7-8 in the course materials section. These are highly recommended for exam preparation.",
        audience: "all",
        audienceLabel: "All My Courses",
        sentAt: "2026-03-10",
        pinned: false,
        category: "general" as const,
        readCount: 89,
        totalCount: 124,
    },
]

// ─── Analytics Data ─────────────────────────────────────────────────
export const analyticsData = {
    // Monthly enrollment trend
    enrollmentTrend: [
        { month: "Sep", students: 95 },
        { month: "Oct", students: 102 },
        { month: "Nov", students: 108 },
        { month: "Dec", students: 110 },
        { month: "Jan", students: 115 },
        { month: "Feb", students: 120 },
        { month: "Mar", students: 124 },
    ],
    // Assignment completion rates per course
    completionRates: [
        { course: "MATH-401", name: "Calculus", rate: 72, avgScore: 88 },
        { course: "MATH-301", name: "Algebra", rate: 85, avgScore: 84 },
        { course: "STAT-201", name: "Statistics", rate: 50, avgScore: 79 },
        { course: "MATH-EXAM", name: "Exam Prep", rate: 32, avgScore: 75 },
        { course: "MATH-201", name: "Geometry", rate: 95, avgScore: 91 },
    ],
    // Weekly engagement (hours spent per day)
    weeklyEngagement: [
        { day: "Mon", hours: 3.2 },
        { day: "Tue", hours: 2.8 },
        { day: "Wed", hours: 4.1 },
        { day: "Thu", hours: 3.5 },
        { day: "Fri", hours: 2.2 },
        { day: "Sat", hours: 5.8 },
        { day: "Sun", hours: 1.4 },
    ],
    // Grade distribution
    gradeDistribution: [
        { grade: "A (90-100)", count: 28, color: "#22c55e" },
        { grade: "B (80-89)", count: 42, color: "#3b82f6" },
        { grade: "C (70-79)", count: 31, color: "#f59e0b" },
        { grade: "D (60-69)", count: 15, color: "#f97316" },
        { grade: "F (<60)", count: 8, color: "#ef4444" },
    ],
}

// ─── Recent Activity ────────────────────────────────────────────────
export const teacherRecentActivity = [
    { text: "Selamawit Girma submitted Homework #4", time: "12 min ago", color: "emerald", icon: "submit" },
    { text: "New student enrolled in MATH-401", time: "1h ago", color: "sky", icon: "enroll" },
    { text: "Abebe Tadesse sent a message", time: "10 min ago", color: "indigo", icon: "message" },
    { text: "You graded Marta Bekele's submission", time: "2h ago", color: "amber", icon: "grade" },
    { text: "Announcement sent to all courses", time: "3h ago", color: "violet", icon: "announce" },
    { text: "New material uploaded to STAT-201", time: "Yesterday", color: "rose", icon: "upload" },
]
